# Generated by Django 3.2 on 2021-05-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='<function static at 0x000001FDE0CC08B0>/img')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=5)),
                ('codigo', models.CharField(max_length=5)),
                ('pobalcion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('latitud', models.FloatField(blank=True, max_length=30, null=True)),
                ('longitud', models.FloatField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
