# Generated by Django 3.2 on 2021-05-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapping', '0003_remove_centros_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='centros',
            name='foto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
